Quantum Exact Simulation Toolkit: QuEST_tn_internal.h File Reference
QuEST_tn_internal.h File Reference
#include "QuEST_tn.h"
Functions
long long int getContractedIndex (long long int activeStateVec1Index, long long int activeStateVec2Index, long long int stateVec1PhysicalSize, long long int stateVec2PhysicalSize, int numTensor1Pq, int numTensor2Pq, int numTensor1UncontractedVqs, int numTensor2UncontractedVqs)
Get the index in the output state vector where an element resulting from a contraction between two tensors should be placed.
void getContractionVqIndices (TensorNetwork tn, int tensor1Index, int tensor2Index, int numContractions, int **tensor1Contractions, int **tensor2Contractions, int *numTensor1UncontractedVqs, int *numTensor2UncontractedVqs, int **tensor1UncontractedVqs, int **tensor2UncontractedVqs)
For a particular contraction of two tensors, generate the lists of virtual qubits that will be contracted and that will remain uncontracted for each tensor.
QCoord getLocalPq (TensorNetwork tn, int globalPq)
int getNumContractions (TensorNetwork tn, int tensor1Index, int tensor2Index)
Get the number of indices that will be contracted over when the two input tensors are contracted.
long long int getStateVectorIndexFromActiveIndex (long long int activeStateIndex, int numPq, int *uncontractedVqs, int numUncontractedVqs)
int getVqVertexIndex (TensorNetwork tn, VqVertex *vqVertex)
void initVirtualControl (Tensor tensor, int vqIndex)
void initVirtualTarget (Tensor tensor, int vqIndex)
Complex recursiveContract (Tensor tensor1, Tensor tensor2, long long int tensor1Offset, long long int tensor2Offset, int *tensor1Contractions, int *tensor2Contractions, int numContractions, int vqIndex)
void remapFirstGlobalPqIndex (TensorNetwork tn)
void remapTensorIndexFromGlobalPq (TensorNetwork tn)
void removeAllVqVertices (TensorNetwork tn, int tensorIndex)
void removeContractedVqVertices (TensorNetwork tn, int tensorIndex, int newTensorIndex, VqVertex *startingVqVertex, VqVertex *prevVqVertexToKeep, int *uncontractedVqs, int numUncontractedVqs, VqVertex **tail, int *foundHead)
Function Documentation
getContractedIndex()
long long int getContractedIndex (long long int activeStateVec1Index, long long int activeStateVec2Index, long long int stateVec1PhysicalSize, long long int stateVec2PhysicalSize, int numTensor1Pq, int numTensor2Pq, int numTensor1UncontractedVqs, int numTensor2UncontractedVqs)
Get the index in the output state vector where an element resulting from a contraction between two tensors should be placed.
Definition at line 128 of file QuEST_tn.c.
References DEBUG_PRINT.
Referenced by contractTensors().
{
     long long int contractedIndex;
     long long int stateVec1IndexInPq, stateVec2IndexInPq;
     long long int sizeOutputHalfBlock, sizeActiveHalfBlock;
     int activeIsLower;
     long long int stateVectorIndex = 0;
     long long int activeIndexInBlock;
     // activeStateVec1Index % sateVec1PhysicalSize = activeStateVec1Index&(stateVec1PhysicalSize-1)
     stateVec1IndexInPq = activeStateVec1Index&(stateVec1PhysicalSize-1);
     stateVec2IndexInPq = activeStateVec2Index&(stateVec2PhysicalSize-1);
     DEBUG_PRINT(("getOutputIndex: t1psize %lld t2psize %lld\n", stateVec1PhysicalSize, stateVec2PhysicalSize));
     contractedIndex = stateVec2IndexInPq*stateVec1PhysicalSize + stateVec1IndexInPq;
     DEBUG_PRINT(("getOuputIndex: contractedIndex %lld\n", contractedIndex));
     // TODO -- seems inefficient given the only thing changing between this and
     // activeStateVectorIndex is number of Pq (if tensor2 has no uncontracted vq?)
     activeIndexInBlock = activeStateVec1Index;
     for (int i=numTensor1UncontractedVqs-1; i>=0; i--){
         // the size of a block of elements in the state vector for an uncontracted virtual qubit
         sizeOutputHalfBlock = 1LL << (numTensor1Pq + numTensor2Pq + i);
         sizeActiveHalfBlock = 1LL << (numTensor1Pq + i);
         activeIsLower = (activeIndexInBlock >= sizeActiveHalfBlock); // TODO -- better to get value of qubit?
         DEBUG_PRINT(("sizeOutput %lld sizeActive %lld isLower %d\n", sizeOutputHalfBlock, sizeActiveHalfBlock, activeIsLower));
         if (activeIsLower) {
             contractedIndex += sizeOutputHalfBlock; // TODO -- replace with predicate
             activeIndexInBlock -= sizeActiveHalfBlock;
         }
     }
     activeIndexInBlock = activeStateVec2Index;
     for (int i=numTensor2UncontractedVqs-1; i>=0; i--){
         // the size of a block of elements in the state vector for an uncontracted virtual qubit
         sizeOutputHalfBlock = 1LL << (numTensor1Pq + numTensor2Pq + numTensor1UncontractedVqs + i);
         sizeActiveHalfBlock = 1LL << (numTensor2Pq + i);
         activeIsLower = (activeIndexInBlock >= sizeActiveHalfBlock); // TODO -- better to get value of qubit?
         DEBUG_PRINT(("sizeOutput %lld sizeActive %lld isLower %d\n", sizeOutputHalfBlock, sizeActiveHalfBlock, activeIsLower));
         if (activeIsLower) {
             contractedIndex += sizeOutputHalfBlock; // TODO -- replace with predicate
             activeIndexInBlock -= sizeActiveHalfBlock;
         }
     }
     return contractedIndex;
 }
getContractionVqIndices()
void getContractionVqIndices (TensorNetwork tn, int tensor1Index, int tensor2Index, int numContractions, int ** tensor1Contractions, int ** tensor2Contractions, int * numTensor1UncontractedVqs, int * numTensor2UncontractedVqs, int ** tensor1UncontractedVqs, int ** tensor2UncontractedVqs)
For a particular contraction of two tensors, generate the lists of virtual qubits that will be contracted and that will remain uncontracted for each tensor.
The number of virtual qubits to contract must be the same for each tensor but the number of uncontracted qubits may differ
Parameters
[in] TensorNetwork tn the tensor network that the two tensors belong to
[in] int tensor1Index the first tensor to contract. This should have the lower index of the two tensors.
[in] int tensor2Index the second tensor to contract
[in] int numContractions the number of indices to contract over
[out] int** tensor1Contractions tensor1 virtual qubits to contract
[out] int** tensor2Contractions tensor2 virtual qubits to contract
[out] int* numTensor1UncontractedVqs number of virtual qubits in tensor1 that represent entanglement with tensors other than tensor2
[out] int* numTensor2UncontractedVqs number of virtual qubits in tensor2 that represent entanglement with tensors other than tensor1
[out] int** tensor1UncontractedVqs virtual qubit indices that will remain uncontracted in tensor1
[out] int** tensor1UncontractedVqs virtual qubit indices that will remain uncontracted in tensor2
Definition at line 74 of file QuEST_tn.c.
References VqVertex::entangledPair, getVqVertexIndex(), VqVertex::nextInTensor, TensorNetwork::numEntanglements, TensorNetwork::tensorHeadVqVertex, and VqVertex::tensorIndex.
Referenced by contractTensors().
{
     // malloc space for array of virtual qubits to contract
     *tensor1Contractions = malloc(numContractions*sizeof(int));
     *tensor2Contractions = malloc(numContractions*sizeof(int));
     // malloc space for array of virtual qubits on each tensor that will not be contracted
     *numTensor1UncontractedVqs = tn.numEntanglements[tensor1Index] - numContractions;
     *numTensor2UncontractedVqs = tn.numEntanglements[tensor2Index] - numContractions;
     *tensor1UncontractedVqs = malloc(*numTensor1UncontractedVqs *
             sizeof(int));
     *tensor2UncontractedVqs = malloc(*numTensor1UncontractedVqs *
             sizeof(int));
     int contractionCount=0;
     int uncontractedCount=0;
     int vertexCount=0;
     VqVertex *tensorVertex, *entangledPair;
     tensorVertex = tn.tensorHeadVqVertex[tensor1Index];
     while (tensorVertex != NULL){
         entangledPair = tensorVertex->entangledPair;
         if (entangledPair->tensorIndex == tensor2Index) {
             (*tensor1Contractions)[contractionCount]=vertexCount++;
             // add indices to contract in second tensor in same order as for first tensor
             int entangledIndex = getVqVertexIndex(tn, entangledPair);
             (*tensor2Contractions)[contractionCount++]=entangledIndex;
         } else {
             (*tensor1UncontractedVqs)[uncontractedCount++]=vertexCount++;
         }
         tensorVertex = tensorVertex->nextInTensor;
     }
     uncontractedCount=0;
     vertexCount=0;
     tensorVertex = tn.tensorHeadVqVertex[tensor2Index];
     while (tensorVertex != NULL){
         entangledPair = tensorVertex->entangledPair;
         if (!(entangledPair->tensorIndex == tensor1Index)) {
             (*tensor2UncontractedVqs)[uncontractedCount++]=vertexCount;
         }
         vertexCount++;
         tensorVertex = tensorVertex->nextInTensor;
     }
 }
getLocalPq()
QCoord getLocalPq (TensorNetwork tn, int globalPq)
Definition at line 657 of file QuEST_tn.c.
References Tensor::firstGlobalPqIndex, QCoord::qIndex, QCoord::tensorIndex, TensorNetwork::tensorIndexFromGlobalPq, and TensorNetwork::tensors.
Referenced by tn_controlledNot().
{
     QCoord localPq;
     localPq.tensorIndex = tn.tensorIndexFromGlobalPq[globalPq];
     localPq.qIndex = globalPq - tn.tensors[localPq.tensorIndex].firstGlobalPqIndex;
     return localPq;
 }
getNumContractions()
int getNumContractions (TensorNetwork tn, int tensor1Index, int tensor2Index)
Get the number of indices that will be contracted over when the two input tensors are contracted.
These correspond to all the virtual qubit indices that represent entanglement between the two tensors.
Returns
the number of indices to contract
Parameters
[in] TensorNetwork tn the tensor network that the two tensors belong to
[in] int tensor1Index the first tensor to contract. This should have the lower index of the two tensors.
[in] int tensor2Index the second tensor to contract
Definition at line 41 of file QuEST_tn.c.
References VqVertex::entangledPair, VqVertex::nextInTensor, TensorNetwork::tensorHeadVqVertex, and VqVertex::tensorIndex.
Referenced by contractTensors().
{
     int numContractions = 0;
     VqVertex *tensor1Vertex, *entangledPair;
     tensor1Vertex = tn.tensorHeadVqVertex[tensor1Index];
     while (tensor1Vertex != NULL){
         entangledPair = tensor1Vertex->entangledPair;
         if (entangledPair->tensorIndex == tensor2Index) numContractions++;
         tensor1Vertex = tensor1Vertex->nextInTensor;
     }
     return numContractions;
 }
getStateVectorIndexFromActiveIndex()
long long int getStateVectorIndexFromActiveIndex (long long int activeStateIndex, int numPq, int * uncontractedVqs, int numUncontractedVqs)
Definition at line 179 of file QuEST_tn.c.
Referenced by contractTensors().
{
     long long int sizeHalfBlock, sizeActiveHalfBlock;
     int activeIsLower;
     long long int activeStatePhysicalSize = 1LL << numPq;
     long long int indexInPhysicalQubitBlock = activeStateIndex&(activeStatePhysicalSize-1);
     long long int stateVectorIndex = indexInPhysicalQubitBlock;
     long long int activeIndexInBlock = activeStateIndex;
     for (int i=numUncontractedVqs-1; i>=0; i--){
         int vqIndex = uncontractedVqs[i];
         // the size of a block of elements in the state vector for an uncontracted virtual qubit
         sizeHalfBlock = 1LL << (numPq + vqIndex);
         sizeActiveHalfBlock = 1LL << (numPq + i);
         activeIsLower = (activeIndexInBlock >= sizeActiveHalfBlock); // TODO -- better to get value of qubit?
         if (activeIsLower) {
             stateVectorIndex += sizeHalfBlock; // TODO -- replace with predicate
             activeIndexInBlock -= sizeActiveHalfBlock;
         }
    }
     return stateVectorIndex;
 }
getVqVertexIndex()
int getVqVertexIndex (TensorNetwork tn, VqVertex * vqVertex)
Definition at line 666 of file QuEST_tn.c.
References VqVertex::nextInTensor, TensorNetwork::numEntanglements, and VqVertex::tensorIndex.
Referenced by getContractionVqIndices(), and printTensorNetwork().
{
     int verticesUntilEndInclusive=0;
     int totalVertices = tn.numEntanglements[vqVertex->tensorIndex];
     if (vqVertex == NULL) return -1;
     while (vqVertex != NULL){
         verticesUntilEndInclusive++;
         vqVertex = vqVertex->nextInTensor;
     }
     return totalVertices - verticesUntilEndInclusive;
 }
initVirtualControl()
void initVirtualControl (Tensor tensor, int vqIndex)
Definition at line 620 of file QuEST_tn.c.
References Tensor::qureg.
Referenced by tn_controlledNot().
{
     // initialize qubit vqIndex to |0> + |1>
     // NOTE: not (1/sqrt(2))(|0> + |1>)
     // TODO: add API funtions to do this instead?
     Qureg qureg = tensor.qureg;
     long long int stateVecSize;
     long long int index;
     // dimension of the state vector
     // TODO: This won't work in parallel
     stateVecSize = 1LL << vqIndex;
     qreal *stateVecReal = qureg.stateVec.real;
     qreal *stateVecImag = qureg.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecSize, stateVecReal, stateVecImag) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<stateVecSize; index++) {
             stateVecReal[index+stateVecSize] = stateVecReal[index];
             stateVecImag[index+stateVecSize] = stateVecImag[index];
         }
     }
 }
initVirtualTarget()
void initVirtualTarget (Tensor tensor, int vqIndex)
Definition at line 614 of file QuEST_tn.c.
References Tensor::qureg.
Referenced by tn_controlledNot().
{
     // place target virtual qubit in the zero state
      collapseToOutcome(tensor.qureg, vqIndex, 0);
 }
recursiveContract()
Complex recursiveContract (Tensor tensor1, Tensor tensor2, long long int tensor1Offset, long long int tensor2Offset, int * tensor1Contractions, int * tensor2Contractions, int numContractions, int vqIndex)
Definition at line 202 of file QuEST_tn.c.
References DEBUG_PRINT, Tensor::numPq, Tensor::qureg, and recursiveContract().
Referenced by contractTensors(), and recursiveContract().
{
     DEBUG_PRINT(("recursive step. vqIndex: %d t1vqToContract %d\n", vqIndex, tensor1Contractions[vqIndex]));
     //TODO -- numPq will need to be numPq + numUnusedLowVq
     long long int tensor1OffsetNew = tensor1Offset + (1LL << (tensor1.numPq+tensor1Contractions[vqIndex]) );
     long long int tensor2OffsetNew = tensor2Offset + (1LL << (tensor2.numPq+tensor2Contractions[vqIndex]) );
     DEBUG_PRINT(("tensor1Offset %lld tensor2Offset %lld\n", tensor1Offset, tensor2Offset));
     DEBUG_PRINT(("tensor1OffsetNew %lld tensor2OffsetNew %lld\n", tensor1OffsetNew, tensor2OffsetNew));
     DEBUG_PRINT(("num pq %d contraction index %d\n", tensor1.numPq, tensor1Contractions[vqIndex]));
     if (vqIndex==numContractions-1){
         Qureg qureg1 = tensor1.qureg;
         Qureg qureg2 = tensor2.qureg;
         qreal *stateVec1Real = qureg1.stateVec.real;
         qreal *stateVec1Imag = qureg1.stateVec.imag;
         qreal *stateVec2Real = qureg2.stateVec.real;
         qreal *stateVec2Imag = qureg2.stateVec.imag;
         qreal sumReal=0;
         qreal sumImag=0;
         // vqIndex == 0
         // Real component
         sumReal += stateVec1Real[tensor1Offset] *
             stateVec2Real[tensor2Offset];
         sumReal += -stateVec1Imag[tensor1Offset] *
             stateVec2Imag[tensor2Offset];
         // Imag component
         sumImag += stateVec1Imag[tensor1Offset] *
             stateVec2Real[tensor2Offset];
         sumImag += stateVec1Real[tensor1Offset] *
             stateVec2Imag[tensor2Offset];
         // vqIndex == 1
         // Real component
         sumReal += stateVec1Real[tensor1OffsetNew] *
             stateVec2Real[tensor2OffsetNew];
         sumReal += -stateVec1Imag[tensor1OffsetNew] *
             stateVec2Imag[tensor2OffsetNew];
         // Imag component
         sumImag += stateVec1Imag[tensor1OffsetNew] *
             stateVec2Real[tensor2OffsetNew];
         sumImag += stateVec1Real[tensor1OffsetNew] *
             stateVec2Imag[tensor2OffsetNew];
         Complex sum;
         sum.real = sumReal; sum.imag = sumImag;
         return sum;
     } else {
         Complex sumPart1, sumPart2, sum;
             sumPart1 = recursiveContract(tensor1, tensor2, tensor1Offset, tensor2Offset,
                 tensor1Contractions, tensor2Contractions, numContractions, vqIndex+1);
             sumPart2 = recursiveContract(tensor1, tensor2, tensor1OffsetNew, tensor2OffsetNew,
                 tensor1Contractions, tensor2Contractions, numContractions, vqIndex+1);
         sum.real = sumPart1.real + sumPart2.real;
         sum.imag = sumPart1.imag + sumPart2.imag;
         return sum;
     }
 }
remapFirstGlobalPqIndex()
void remapFirstGlobalPqIndex (TensorNetwork tn)
Definition at line 482 of file QuEST_tn.c.
References Tensor::firstGlobalPqIndex, Tensor::numPq, TensorNetwork::numTensors, and TensorNetwork::tensors.
Referenced by contractTensors().
{
     int globalPqOffset = 0;
     for (int i=0; i<tn.numTensors; i++){
         Tensor tensor = tn.tensors[i];
         tensor.firstGlobalPqIndex = globalPqOffset;
         globalPqOffset += tensor.numPq;
     }
 }
remapTensorIndexFromGlobalPq()
void remapTensorIndexFromGlobalPq (TensorNetwork tn)
Definition at line 471 of file QuEST_tn.c.
References Tensor::numPq, TensorNetwork::numTensors, TensorNetwork::tensorIndexFromGlobalPq, and TensorNetwork::tensors.
Referenced by contractTensors().
{
     int currentPq = 0;
     for (int i=0; i<tn.numTensors; i++){
         Tensor tensor = tn.tensors[i];
         for (int j=0; j<tensor.numPq; j++){
             tn.tensorIndexFromGlobalPq[currentPq++] = i;
         }
     }
 }
removeAllVqVertices()
void removeAllVqVertices (TensorNetwork tn, int tensorIndex)
Definition at line 491 of file QuEST_tn.c.
References VqVertex::nextInTensor, and TensorNetwork::tensorHeadVqVertex.
{
     VqVertex *prevVqVertex;
     VqVertex *vqVertex = tn.tensorHeadVqVertex[tensorIndex];
     while (vqVertex != NULL){
         prevVqVertex = vqVertex;
         vqVertex = vqVertex->nextInTensor;
         free(prevVqVertex);
     }
 }
removeContractedVqVertices()
void removeContractedVqVertices (TensorNetwork tn, int tensorIndex, int newTensorIndex, VqVertex * startingVqVertex, VqVertex * prevVqVertexToKeep, int * uncontractedVqs, int numUncontractedVqs, VqVertex ** tail, int * foundHead)
Definition at line 501 of file QuEST_tn.c.
References VqVertex::nextInTensor, TensorNetwork::tensorHeadVqVertex, and VqVertex::tensorIndex.
Referenced by contractTensors().
{
     VqVertex *vqVertex, *prevVqVertex;
     int vqVertexCount = 0;
     int uncontractedVqCount = 0;
     vqVertex = startingVqVertex;
     // Search through vertices and keep those which are in uncontractedVqs.
     // Free vertices which no longer need to be stored
     while (vqVertex != NULL){
         if (uncontractedVqCount<numUncontractedVqs) {
             if (vqVertexCount++ == uncontractedVqs[uncontractedVqCount]) {
                 // keep
                 if (vqVertex->tensorIndex != newTensorIndex) vqVertex->tensorIndex = newTensorIndex;
                 if (!(*foundHead)) {
                     tn.tensorHeadVqVertex[tensorIndex] = vqVertex;
                     *foundHead = 1;
                 }
                 if (prevVqVertexToKeep!=NULL){
                     prevVqVertexToKeep->nextInTensor = vqVertex;
                 }
                 prevVqVertexToKeep = vqVertex;
                 vqVertex = vqVertex->nextInTensor;
                 uncontractedVqCount++;
             } else {
                 // discard
                 prevVqVertex = vqVertex;
                 vqVertex = vqVertex->nextInTensor;
                 free(prevVqVertex);
             }
         } else {
             // discard
             prevVqVertex = vqVertex;
             vqVertex = vqVertex->nextInTensor;
             free(prevVqVertex);
         }
     }
     *tail = prevVqVertexToKeep;
     if (prevVqVertexToKeep != NULL){
         prevVqVertexToKeep->nextInTensor=NULL;
     }
 }