Quantum Exact Simulation Toolkit: QuEST_tn.h File Reference
QuEST_tn.h File Reference
#include "QuEST.h"
Data Structures
struct QCoord
Naming conventions:
struct Tensor
struct TensorNetwork
struct VqVertex
Typedefs
typedef struct QCoord QCoord
Naming conventions:
typedef struct Tensor Tensor
typedef struct TensorNetwork TensorNetwork
typedef struct VqVertex VqVertex
Functions
void contractTensorNetwork (TensorNetwork tn, QuESTEnv env)
Contract all tensors in a tensor network one by one.
void contractTensors (TensorNetwork tn, int tensor1, int tensor2, QuESTEnv env)
Replaces the tensor object at index tensor1 in the tensor network with the contraction of tensor1 and tensor 2.
TensorNetwork createTensorNetwork (int numTensors, int *numPqPerTensor, int *numVqPerTensor, QuESTEnv env)
Allocate memory for and initialize a new tensor network object given the number of physical qubits and maximum number of virtual qubits in each tensor.
void printTensorNetwork (TensorNetwork tn)
Print all tensors in a tensor network and their entanglement with other tensors.
void tn_controlledNot (TensorNetwork tn, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate on qubits in a tensor network.
void tn_unitary (TensorNetwork tn, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
Typedef Documentation
QCoord
typedef struct QCoord QCoord
Naming conventions:
vq = virtual qubit pq = physical qubit These are not capitalised by default to distinguish ordinary vars from structs such as VqVertex, which do have the first letter capitalised.
Unless marked as global in the name, all var names that refer to qubit indices refer to local index within a tensor and qubit type. i.e. physical qubits in tensor 2 start from index 0, and virtual qubits in tensor 2 also start from index 0.
In a contraction, the two tensors are referred to as tensor1 and tensor2, where tensor1 is the tensor with the lower index in TensorNetwork.tensors
In a contraction, all shared (virtual qubit) indices between tensor1 and tensor2 will be contracted. The lists of virtual qubit indices corresponding to these contractions are referred to as tensor1Contractions and tensor2Contractions. The lists of any other virtual qubits which are not being contracted as they represent entanglements with other tensors, are referred to as tensor1UncontractedVqs and tensor2UncontractedVqs.
Tensor
typedef struct Tensor Tensor
TensorNetwork
typedef struct TensorNetwork TensorNetwork
VqVertex
typedef struct VqVertex VqVertex
Function Documentation
contractTensorNetwork()
void contractTensorNetwork (TensorNetwork tn, QuESTEnv env)
Contract all tensors in a tensor network one by one.
The simplest strategy – contract tensor 0 with every other tensor in turn Output will be stored as tensor 0.
Parameters
[in,out] TensorNetwork tn tensor network to contract
[in] QuESTEnv env QuEST environment object
Definition at line 24 of file QuEST_tn.c.
References contractTensors(), and TensorNetwork::numTensors.
{
     for (int i=1; i<tn.numTensors; i++){
         contractTensors(tn, 0, i, env);
     }
 }
contractTensors()
void contractTensors (TensorNetwork tn, int tensor1, int tensor2, QuESTEnv env)
Replaces the tensor object at index tensor1 in the tensor network with the contraction of tensor1 and tensor 2.
All virtual qubits linking the two tensors are contracted in this operation. There may be virtual qubits left over after the contraction, corresponding to entanglement with other tensors in the network.
The ordering of qubits in the output tensor from lowest to highest is as follows: tensor1 physical qubits, tensor2 physical qubits, tensor1 virtual qubits, tensor2 virtual qubits.
Parameters
[in,out] TensorNetwork tn the tensor network the two tensors belong to
[in] int tensor1 the index of the first tensor to contract
[in] int tensor1 the index of the second tensor to contract
[in] QuESTEnv env the QuEST environment object
Definition at line 269 of file QuEST_tn.c.
References DEBUG_PRINT, getContractedIndex(), getContractionVqIndices(), getNumContractions(), getStateVectorIndexFromActiveIndex(), VqVertex::nextInTensor, Tensor::nextVqIndex, TensorNetwork::numEntanglements, Tensor::numPq, Tensor::numVq, Tensor::qureg, recursiveContract(), remapFirstGlobalPqIndex(), remapTensorIndexFromGlobalPq(), removeContractedVqVertices(), TensorNetwork::tensorHeadVqVertex, TensorNetwork::tensors, and TensorNetwork::tensorTailVqVertex.
Referenced by contractTensorNetwork(), and main().
{
     // always store new tensor in the smaller tensor index
     if (tensor2Index < tensor1Index){
         int tensorIndexTmp = tensor1Index;
         tensor1Index = tensor2Index;
         tensor2Index = tensorIndexTmp;
     }
     Tensor tensor1 = tn.tensors[tensor1Index];
     Tensor tensor2 = tn.tensors[tensor2Index];
     Tensor outputTensor;
     int numContractions = getNumContractions(tn, tensor1Index, tensor2Index);
     DEBUG_PRINT(("numContractions: %d\n", numContractions));
     int *tensor1Contractions, *tensor2Contractions;
     int *tensor1UncontractedVqs, *tensor2UncontractedVqs;
     int numTensor1UncontractedVqs=0, numTensor2UncontractedVqs=0;
     getContractionVqIndices(tn, tensor1Index, tensor2Index, numContractions,
             &tensor1Contractions, &tensor2Contractions,
             &numTensor1UncontractedVqs, &numTensor2UncontractedVqs,
             &tensor1UncontractedVqs, &tensor2UncontractedVqs);
     DEBUG_PRINT(("tensor1Contractions: "));
     for (int p=0; p<numContractions; p++) {DEBUG_PRINT(("%d ", tensor1Contractions[p])); }
     DEBUG_PRINT(("\ntensor2Contractions: "));
     for (int p=0; p<numContractions; p++) {DEBUG_PRINT(("%d ", tensor2Contractions[p])); }
     DEBUG_PRINT(("\ntensor1UncontractedVqs: "));
     for (int p=0; p<numTensor1UncontractedVqs; p++) {DEBUG_PRINT(("%d ", tensor1UncontractedVqs[p])); }
     DEBUG_PRINT(("\ntensor2UncontractedVqs: "));
     for (int p=0; p<numTensor2UncontractedVqs; p++) {DEBUG_PRINT(("%d ", tensor2UncontractedVqs[p])); }
     DEBUG_PRINT(("\n"));
     int totalNumPq = tensor1.numPq + tensor2.numPq;
     int totalNumVq = numTensor1UncontractedVqs + numTensor2UncontractedVqs;
     int totalNumQ = totalNumPq + totalNumVq;
     long long int contractedStateVecSize, stateVec1Size, stateVec2Size, activeStateVec1Size, activeStateVec2Size;
     long long int contractedIndex, stateVec1Index, stateVec2Index, activeStateVec1Index, activeStateVec2Index;
     long long int stateVec1PhysicalSize, stateVec2PhysicalSize;
     contractedStateVecSize = 1LL << totalNumQ;
     stateVec1Size = 1LL << tensor1.numPq + tensor1.numVq;
     stateVec2Size = 1LL << tensor2.numPq + tensor1.numVq;
     stateVec1PhysicalSize = 1LL << tensor1.numPq;
     stateVec2PhysicalSize = 1LL << tensor2.numPq;
     activeStateVec1Size = stateVec1Size >> numContractions;
     activeStateVec2Size = stateVec2Size >> numContractions;
     Qureg contractedQureg = createQureg(totalNumQ, env);
     Qureg qureg1 = tensor1.qureg;
     Qureg qureg2 = tensor2.qureg;
     qreal sumReal, sumImag;
     qreal *stateVec1Real = qureg1.stateVec.real;
     qreal *stateVec1Imag = qureg1.stateVec.imag;
     qreal *stateVec2Real = qureg2.stateVec.real;
     qreal *stateVec2Imag = qureg2.stateVec.imag;
     for (activeStateVec2Index=0; activeStateVec2Index<activeStateVec2Size; activeStateVec2Index++) {
         for (activeStateVec1Index=0; activeStateVec1Index<activeStateVec1Size; activeStateVec1Index++) {
             stateVec1Index = getStateVectorIndexFromActiveIndex(activeStateVec1Index, tensor1.numPq,
                     tensor1UncontractedVqs, numTensor1UncontractedVqs);
             stateVec2Index = getStateVectorIndexFromActiveIndex(activeStateVec2Index, tensor2.numPq,
                     tensor2UncontractedVqs, numTensor2UncontractedVqs);
             DEBUG_PRINT(("-------------------------\n"));
             DEBUG_PRINT(("t1: ai %lld si %lld\n", activeStateVec1Index, stateVec1Index));
             DEBUG_PRINT(("t2: ai %lld si %lld\n", activeStateVec2Index, stateVec2Index));
             Complex sum;
             sum = recursiveContract(tensor1, tensor2, stateVec1Index, stateVec2Index,
                 tensor1Contractions, tensor2Contractions, numContractions, 0);
             contractedIndex = getContractedIndex(activeStateVec1Index, activeStateVec2Index,
                     stateVec1PhysicalSize, stateVec2PhysicalSize, tensor1.numPq, tensor2.numPq,
                     numTensor1UncontractedVqs, numTensor2UncontractedVqs);
             DEBUG_PRINT(("OUTPUT: %lld VALUE: %f\n", contractedIndex, sum.real));
             contractedQureg.stateVec.real[contractedIndex] = sum.real;
             contractedQureg.stateVec.imag[contractedIndex] = sum.imag;
         }
     }
     // Update vqVertices in tn lists
     // first tensor's vqVertices
     VqVertex *tail=NULL;
     int foundHead=0;
     removeContractedVqVertices(tn, tensor1Index, tensor1Index, tn.tensorHeadVqVertex[tensor1Index],
             NULL, tensor1UncontractedVqs, numTensor1UncontractedVqs, &tail, &foundHead);
     // second tensor's vqVertices
     if (foundHead){
         // there was at least one uncontracted index in the first tensor
         tail->nextInTensor = tn.tensorHeadVqVertex[tensor2Index];
         removeContractedVqVertices(tn, tensor2Index, tensor1Index, tail->nextInTensor, tail,
                 tensor2UncontractedVqs, numTensor2UncontractedVqs, &tail, &foundHead);
     } else {
         // there were no uncontracted index in the first tensor
         removeContractedVqVertices(tn, tensor2Index, tensor1Index, tn.tensorHeadVqVertex[tensor2Index],
                 NULL, tensor2UncontractedVqs, numTensor2UncontractedVqs, &tail, &foundHead);
     }
     if (!foundHead) tn.tensorHeadVqVertex[tensor1Index] = NULL;
     tn.tensorTailVqVertex[tensor1Index] = tail;
     if (tail != NULL) tail->nextInTensor = NULL;
     // Update first tensor
     // The output of the contraction is stored in the location of the first tensor
     // in the tensor array.
     destroyQureg(tensor1.qureg, env);
     outputTensor.qureg = contractedQureg;
     outputTensor.numPq = totalNumPq;
     outputTensor.numVq = totalNumVq;
     outputTensor.nextVqIndex = totalNumVq;
     tn.numEntanglements[tensor1Index] = totalNumVq;
     tn.tensors[tensor1Index] = outputTensor;
     // Update second tensor
     // The order of tensors in the tensor array is not changed when two tensors are contracted
     // -- for now, just leave a gap where the second tensor was by setting numPq to 0.
     destroyQureg(tensor2.qureg, env);
     tn.tensors[tensor2Index].numPq = 0;
     tn.tensors[tensor2Index].numVq = 0;
     // Update tn mapping between global qubit indices and (tensor, local qubit index)
     remapTensorIndexFromGlobalPq(tn);
     remapFirstGlobalPqIndex(tn);
 }
createTensorNetwork()
TensorNetwork createTensorNetwork (int numTensors, int * numPqPerTensor, int * numVqPerTensor, QuESTEnv env)
Allocate memory for and initialize a new tensor network object given the number of physical qubits and maximum number of virtual qubits in each tensor.
Initialise all physical qubits to the zero state and virtual qubits to an undefined state.
Parameters
[in] int numTensors the number of tensors in the tensor network
[in] int* numPqPerTensor an array of values corresponding to the number of physical qubits in each tensor
[in] int* numVqPerTensor an array of values corresponding to the maximum number of virtual qubits that could be used in each tensor
[in] QuESTEnv env QuEST environment object
Definition at line 403 of file QuEST_tn.c.
References Tensor::firstGlobalPqIndex, Tensor::nextVqIndex, TensorNetwork::numEntanglements, Tensor::numPq, TensorNetwork::numTensors, Tensor::numVq, Tensor::qureg, TensorNetwork::tensorHeadVqVertex, TensorNetwork::tensorIndexFromGlobalPq, TensorNetwork::tensors, and TensorNetwork::tensorTailVqVertex.
Referenced by main().
                      {
     TensorNetwork tn;
     tn.numTensors = numTensors;
     // allocate memory in tensor object
     tn.tensors = malloc( numTensors*sizeof(*(tn.tensors)) );
     tn.tensorHeadVqVertex = malloc( numTensors*sizeof(*(tn.tensorHeadVqVertex)) );
     tn.tensorTailVqVertex = malloc( numTensors*sizeof(*(tn.tensorTailVqVertex)) );
     tn.numEntanglements = malloc( numTensors*sizeof(*(tn.numEntanglements)) );
     // calculate total number of qubits in system for qubits given per tensor
     int numTotalPq = 0;
     int numTotalVq = 0;
     for (int i=0; i<numTensors; i++){
         numTotalPq += numPqPerTensor[i];
         numTotalVq += numVqPerTensor[i];
     }
     tn.tensorIndexFromGlobalPq = malloc( numTotalPq*sizeof(*(tn.tensorIndexFromGlobalPq)) );
     // populate tensorIndexFromGlobalPq array. This contains duplicated values but should be
     // fast to look up
     int currentPq = 0;
     for (int i=0; i<numTensors; i++){
         int numPqInCurrentTensor = numPqPerTensor[i];
         for (int j=0; j<numPqInCurrentTensor; j++){
             tn.tensorIndexFromGlobalPq[currentPq++] = i;
         }
     }
     int globalPqOffset = 0;
     // populate tensor array
     Tensor tmpTensor;
     for (int i=0; i<numTensors; i++){
         tmpTensor.numPq = numPqPerTensor[i];
         tmpTensor.numVq = numVqPerTensor[i];
         // create qureg object and initialize to zero
         tmpTensor.qureg = createQureg(tmpTensor.numPq + tmpTensor.numVq, env);
         initZeroState(tmpTensor.qureg);
         //if (i==0)statevec_initStateDebugFromOffset(tmpTensor.qureg, 0);
         //if (i==1) hadamard(tmpTensor.qureg, 0);
         //if (i==1) rotateZ(tmpTensor.qureg, 0, 0.3);
         //if (i==0) hadamard(tmpTensor.qureg, 0);
         if (i==0) pauliX(tmpTensor.qureg, 0);
         if (i==0) rotateZ(tmpTensor.qureg, 0, 0.3);
         //if (i==1)statevec_initStateDebugFromOffset(tmpTensor.qureg, 2);
         // for quick conversion to local index from global index
         tmpTensor.firstGlobalPqIndex = globalPqOffset;
         // the next virtual qubit to use
         tmpTensor.nextVqIndex = 0;
         tn.tensors[i] = tmpTensor;
         tn.tensorHeadVqVertex[i] = NULL;
         tn.tensorTailVqVertex[i] = NULL;
         tn.numEntanglements[i] = 0;
         globalPqOffset += tmpTensor.numPq;
     }
     return tn;
 }
printTensorNetwork()
void printTensorNetwork (TensorNetwork tn)
Print all tensors in a tensor network and their entanglement with other tensors.
Parameters
[in] TensorNetwork tn the tensor network to print
Definition at line 677 of file QuEST_tn.c.
References VqVertex::entangledPair, getVqVertexIndex(), VqVertex::nextInTensor, TensorNetwork::numEntanglements, Tensor::numPq, TensorNetwork::numTensors, Tensor::numVq, TensorNetwork::tensorHeadVqVertex, VqVertex::tensorIndex, and TensorNetwork::tensors.
Referenced by main().
{
     printf("\n----- TensorNetwork -------------------- \n");
     printf("%d tensors\n", tn.numTensors);
     for (int i=0; i<tn.numTensors; i++){
         Tensor tensor = tn.tensors[i];
         if (tensor.numPq==0){
             printf("Tensor %d: DELETED BY CONTRACTION\n", i);
         } else {
             printf("Tensor %d: %d physical qubits, %d virtual qubits\n", i, tensor.numPq, tensor.numVq);
             printf("\t%d Entanglements:\n", tn.numEntanglements[i]);
             VqVertex *vqVertex = tn.tensorHeadVqVertex[i];
             VqVertex *entangledPair;
             int vqCount=0;
             while (vqVertex != NULL){
                 entangledPair = vqVertex->entangledPair;
                 int entangledIndex = getVqVertexIndex(tn, entangledPair);
                 printf("\t\tVirtual qubit %d -> tensor %d, virtual qubit %d\n",
                         vqCount++, entangledPair->tensorIndex, entangledIndex);
                 vqVertex = vqVertex->nextInTensor;
             }
         }
     }
     printf("\n");
 //    printf("\n--------------------------------------- \n");
 }
tn_controlledNot()
void tn_controlledNot (TensorNetwork tn, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate on qubits in a tensor network.
If the two qubits are in different tensors, also track the entanglement introduced between those tensors using virtual qubits.
Note that the control and target qubits should be supplied as global qubit indices over all physical qubits in all tensors.
This applies pauliX to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] TensorNetwork tn the tensor network containing the control and target qubits
[in] controlQubit nots the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 549 of file QuEST_tn.c.
References DEBUG_PRINT, VqVertex::entangledPair, getLocalPq(), initVirtualControl(), initVirtualTarget(), VqVertex::nextInTensor, Tensor::nextVqIndex, TensorNetwork::numEntanglements, Tensor::numPq, QCoord::qIndex, Tensor::qureg, TensorNetwork::tensorHeadVqVertex, QCoord::tensorIndex, VqVertex::tensorIndex, TensorNetwork::tensors, and TensorNetwork::tensorTailVqVertex.
Referenced by main().
{
     QCoord controlPqLocal = getLocalPq(tn, controlQubit);
     QCoord targetPqLocal = getLocalPq(tn, targetQubit);
     Tensor *controlTensor = &(tn.tensors[controlPqLocal.tensorIndex]);
     if (controlPqLocal.tensorIndex == targetPqLocal.tensorIndex){
         // qubits are in same tensor/qureg. Just do a normal qureg operation
         controlledNot(controlTensor->qureg, controlPqLocal.qIndex, targetPqLocal.qIndex);
     } else {
         // qubits are in different tensor/qureg
         // do control tensor half
         // TODO: note this won't work if doing multiple different operations on the same tensor in parallel
         int virtualTargetIndex = controlTensor->nextVqIndex;
         // TODO -- shouldn't have to initialize virtual target when virtual qubits are
         // automatically initialized in the zero state
         initVirtualTarget(*controlTensor, virtualTargetIndex + controlTensor->numPq);
         controlTensor->nextVqIndex = controlTensor->nextVqIndex + 1;
         DEBUG_PRINT(("controlled not 1: %d %d\n", controlPqLocal.qIndex, virtualTargetIndex + controlTensor->numPq));
         controlledNot(controlTensor->qureg, controlPqLocal.qIndex, virtualTargetIndex + controlTensor->numPq);
         // do target tensor half
         // TODO: note this won't work if doing multiple different operations on the same tensor in parallel
         Tensor *targetTensor = &(tn.tensors[targetPqLocal.tensorIndex]);
         int virtualControlIndex = targetTensor->nextVqIndex;
         initVirtualControl(*targetTensor, virtualControlIndex + targetTensor->numPq);
         targetTensor->nextVqIndex = targetTensor->nextVqIndex + 1;
         DEBUG_PRINT(("controlled not 2: %d %d\n", virtualControlIndex + targetTensor->numPq, targetPqLocal.qIndex));
         controlledNot(targetTensor->qureg, virtualControlIndex + targetTensor->numPq, targetPqLocal.qIndex);
         // TODO -- change t1, t2 to control/target
         // update adjacency list.
         // tensor1
         VqVertex *tensor1VqVertex = malloc(sizeof(*tensor1VqVertex));
         tensor1VqVertex->nextInTensor = NULL;
         tensor1VqVertex->tensorIndex = targetPqLocal.tensorIndex;
         if (tn.tensorTailVqVertex[targetPqLocal.tensorIndex] != NULL){
                 tn.tensorTailVqVertex[targetPqLocal.tensorIndex]->nextInTensor = tensor1VqVertex;
         }
         tn.tensorTailVqVertex[targetPqLocal.tensorIndex] = tensor1VqVertex;
         if (tn.numEntanglements[targetPqLocal.tensorIndex]==0) {
             tn.tensorHeadVqVertex[targetPqLocal.tensorIndex] = tensor1VqVertex;
         }
         // tensor2
         VqVertex *tensor2VqVertex = malloc(sizeof(*tensor2VqVertex));
         tensor2VqVertex->nextInTensor = NULL;
         tensor2VqVertex->tensorIndex = controlPqLocal.tensorIndex;
         if (tn.tensorTailVqVertex[controlPqLocal.tensorIndex] != NULL){
                 tn.tensorTailVqVertex[controlPqLocal.tensorIndex]->nextInTensor = tensor2VqVertex;
         }
         tn.tensorTailVqVertex[controlPqLocal.tensorIndex] = tensor2VqVertex;
         if (tn.numEntanglements[controlPqLocal.tensorIndex]==0) {
             tn.tensorHeadVqVertex[controlPqLocal.tensorIndex] = tensor2VqVertex;
         }
         tensor1VqVertex->entangledPair = tensor2VqVertex;
         tensor2VqVertex->entangledPair = tensor1VqVertex;
         tn.numEntanglements[controlPqLocal.tensorIndex]++;
         tn.numEntanglements[targetPqLocal.tensorIndex]++;
     }
 }
tn_unitary()
void tn_unitary (TensorNetwork tn, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
The passed 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Note that the target qubit should be supplied as a global qubit index over all physical qubits in all tensors.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented), or matrix u is not unitary.